name: Primary Key Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      postgres-host: ${{ steps.postgres.outputs.postgres-host }}
      postgres-port: ${{ steps.postgres.outputs.postgres-port }}
      postgres-database: ${{ steps.postgres.outputs.postgres-database }}
      postgres-username: ${{ steps.postgres.outputs.postgres-username }}
      postgres-password: ${{ steps.postgres.outputs.postgres-password }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up PostgreSQL 18
      uses: ikalnytskyi/action-setup-postgres@v8
      id: postgres
      with:
        postgres-version: "18"
        username: tester
        password: password
        database: testdb
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      id: python
      with:
        python-version: "3.13"
    - name: Install dependencies
      id: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Lint with flake8
      id: lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Generate Environment File
      id: generate-env-file
      run: |
        echo "DB_HOST=${{ needs.install.outputs.postgres-host }}" >> .env
        echo "DB_PORT=${{ needs.install.outputs.postgres-port }}" >> .env
        echo "DB_NAME=${{ needs.install.outputs.postgres-database }}" >> .env
        echo "DB_USER=${{ needs.install.outputs.postgres-username }}" >> .env
        echo "DB_PASSWORD=${{ needs.install.outputs.postgres-password }}" >> .env
    - name: Test with pytest
      id: pytest
      run: |
        pytest --suppress-no-test-exit-code

